"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-29 11:04:49.557873

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_challenges",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("target", sa.String(length=254), nullable=False),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=False),
        sa.Column("captcha_verified", sa.Boolean(), nullable=False),
        sa.Column("failed_attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("auth_challenges", schema=None) as batch_op:
        batch_op.create_index(
            "idx_auth_challenge_ip_created", ["ip_address", "created_at"], unique=False
        )
        batch_op.create_index(
            "idx_auth_challenge_target_created", ["channel", "target", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_auth_challenges_channel"), ["channel"], unique=False)
        batch_op.create_index(batch_op.f("ix_auth_challenges_target"), ["target"], unique=False)

    op.create_table(
        "supplier_inquiries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("main_business", sa.String(length=500), nullable=False),
        sa.Column("country", sa.String(length=5), nullable=False),
        sa.Column("contact_name", sa.String(length=150), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("remark", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("display_name", sa.String(length=150), nullable=False),
        sa.Column("nickname", sa.String(length=150), nullable=False),
        sa.Column("country_code", sa.String(length=10), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("avatar", sa.String(length=500), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_platform_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_phone"), ["phone"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("site_type", sa.String(length=30), nullable=False),
        sa.Column("lead_acquisition_requirement", sa.Text(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Integer(), nullable=False),
        sa.Column("daily_lead_limit", sa.Integer(), nullable=False),
        sa.Column("vendure_channels_token", sa.String(length=255), nullable=False),
        sa.Column("vendure_url", sa.String(length=500), nullable=False),
        sa.Column("onboarding_state", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workspaces", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workspaces_slug"), ["slug"], unique=True)

    op.create_table(
        "agent_conversations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_conversations", schema=None) as batch_op:
        batch_op.create_index(
            "idx_agent_conversation_workspace_user", ["workspace_id", "user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_agent_conversations_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_agent_conversations_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_conversations_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=12), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index(
            "idx_api_key_workspace_active", ["workspace_id", "is_active"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_api_keys_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_keys_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_api_keys_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=True),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(
            "idx_audit_workspace_created", ["workspace_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_logs_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_logs_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "buyer_inquiries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("assigned_workspace_id", sa.String(length=36), nullable=True),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("required_product", sa.String(length=500), nullable=False),
        sa.Column("country", sa.String(length=5), nullable=False),
        sa.Column("contact_name", sa.String(length=150), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("remark", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["assigned_workspace_id"], ["workspaces.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("buyer_inquiries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_buyer_inquiries_assigned_workspace_id"),
            ["assigned_workspace_id"],
            unique=False,
        )

    op.create_table(
        "categories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "parent_id", "name"),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_categories_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=100), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "scope", "key"),
    )
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_idempotency_records_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "leads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("external_ref", sa.String(length=120), nullable=False),
        sa.Column("merchant_name", sa.String(length=200), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("contact_person", sa.String(length=150), nullable=False),
        sa.Column("country", sa.String(length=5), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("zip_code", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=False),
        sa.Column("country_code", sa.String(length=10), nullable=False),
        sa.Column("whatsapp", sa.String(length=50), nullable=False),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("recommendation_score", sa.Integer(), nullable=False),
        sa.Column("recommendation_reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "source", "external_ref"),
    )
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.create_index("idx_lead_workspace_stage", ["workspace_id", "stage"], unique=False)
        batch_op.create_index(batch_op.f("ix_leads_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("topic", sa.String(length=100), nullable=False),
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.String(length=36), nullable=False),
        sa.Column("deduplication_key", sa.String(length=200), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deduplication_key"),
    )
    with op.batch_alter_table("outbox_messages", schema=None) as batch_op:
        batch_op.create_index(
            "idx_outbox_status_available", ["status", "available_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_outbox_messages_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_outbox_messages_topic"), ["topic"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_outbox_messages_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "shopify_configs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("store_url", sa.String(length=500), nullable=False),
        sa.Column("api_version", sa.String(length=20), nullable=False),
        sa.Column("api_key_encrypted", sa.Text(), nullable=False),
        sa.Column("api_secret_encrypted", sa.Text(), nullable=False),
        sa.Column("grant_type", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id"),
    )
    with op.batch_alter_table("shopify_configs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_shopify_configs_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_shopify_configs_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "workspace_invitations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("token_prefix", sa.String(length=20), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("invited_by", sa.String(length=36), nullable=False),
        sa.Column("accepted_by", sa.String(length=36), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["accepted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["invited_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("workspace_invitations", schema=None) as batch_op:
        batch_op.create_index(
            "idx_workspace_invitation_workspace_status", ["workspace_id", "status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_workspace_invitations_email"), ["email"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_workspace_invitations_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "workspace_members",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "user_id"),
    )
    with op.batch_alter_table("workspace_members", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workspace_members_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_workspace_members_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "workspace_prompt_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("daily_lead_limit", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "version"),
    )
    with op.batch_alter_table("workspace_prompt_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workspace_prompt_versions_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "agent_executions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("requested_by", sa.String(length=36), nullable=False),
        sa.Column("execution_key", sa.String(length=128), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("tool_input", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("result_payload", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["agent_conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["requested_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "execution_key"),
    )
    with op.batch_alter_table("agent_executions", schema=None) as batch_op:
        batch_op.create_index(
            "idx_agent_execution_conversation_status", ["conversation_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_executions_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_executions_requested_by"), ["requested_by"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_agent_executions_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_agent_executions_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "agent_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("event_payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["agent_conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_messages", schema=None) as batch_op:
        batch_op.create_index(
            "idx_agent_message_conversation_created",
            ["conversation_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_agent_messages_conversation_id"), ["conversation_id"], unique=False
        )

    op.create_table(
        "contact_activities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("lead_id", sa.String(length=36), nullable=False),
        sa.Column("activity_type", sa.String(length=30), nullable=False),
        sa.Column("direction", sa.String(length=30), nullable=False),
        sa.Column("channel", sa.String(length=30), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("sender", sa.String(length=254), nullable=False),
        sa.Column("recipient", sa.String(length=254), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contact_activities", schema=None) as batch_op:
        batch_op.create_index(
            "idx_activity_workspace_created", ["workspace_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contact_activities_lead_id"), ["lead_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contact_activities_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("lead_id", sa.String(length=36), nullable=True),
        sa.Column("order_number", sa.String(length=60), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("order_status", sa.String(length=30), nullable=False),
        sa.Column("payment_status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "order_number"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_orders_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "products",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("category_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("specification_template", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("external_ids", sa.JSON(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_products_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "agent_approvals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("execution_id", sa.String(length=36), nullable=False),
        sa.Column("requested_by", sa.String(length=36), nullable=False),
        sa.Column("decided_by", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["decided_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["execution_id"], ["agent_executions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requested_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("execution_id"),
    )
    with op.batch_alter_table("agent_approvals", schema=None) as batch_op:
        batch_op.create_index(
            "idx_agent_approval_workspace_status", ["workspace_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_approvals_execution_id"), ["execution_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_approvals_requested_by"), ["requested_by"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_agent_approvals_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_agent_approvals_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "product_variants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("sku_code", sa.String(length=100), nullable=False),
        sa.Column("specifications", sa.JSON(), nullable=False),
        sa.Column("minimum_order_quantity", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("stock_quantity", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("external_ids", sa.JSON(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "sku_code"),
    )
    with op.batch_alter_table("product_variants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_product_variants_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_product_variants_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "quotes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("lead_id", sa.String(length=36), nullable=True),
        sa.Column("buyer_inquiry_id", sa.String(length=36), nullable=True),
        sa.Column("order_id", sa.String(length=36), nullable=True),
        sa.Column("quote_number", sa.String(length=55), nullable=False),
        sa.Column("customer_name", sa.String(length=200), nullable=False),
        sa.Column("customer_email", sa.String(length=254), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.Column("subtotal_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("shipping_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("terms", sa.Text(), nullable=False),
        sa.Column("decision_note", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("discount_amount >= 0", name="ck_quote_discount_nonnegative"),
        sa.CheckConstraint("shipping_amount >= 0", name="ck_quote_shipping_nonnegative"),
        sa.CheckConstraint("subtotal_amount >= 0", name="ck_quote_subtotal_nonnegative"),
        sa.CheckConstraint("tax_amount >= 0", name="ck_quote_tax_nonnegative"),
        sa.CheckConstraint("total_amount >= 0", name="ck_quote_total_nonnegative"),
        sa.ForeignKeyConstraint(["buyer_inquiry_id"], ["buyer_inquiries.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
        sa.UniqueConstraint("workspace_id", "quote_number"),
    )
    with op.batch_alter_table("quotes", schema=None) as batch_op:
        batch_op.create_index(
            "idx_quote_workspace_status", ["workspace_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_quotes_buyer_inquiry_id"), ["buyer_inquiry_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_quotes_lead_id"), ["lead_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_quotes_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "shipments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("carrier", sa.String(length=100), nullable=False),
        sa.Column("tracking_number", sa.String(length=100), nullable=False),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shipping_status", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("updated_by", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shipments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shipments_order_id"), ["order_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_shipments_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "inventory_movements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("variant_id", sa.String(length=36), nullable=False),
        sa.Column("movement_type", sa.String(length=30), nullable=False),
        sa.Column("quantity_delta", sa.Integer(), nullable=False),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("reference", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["variant_id"], ["product_variants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inventory_movements", schema=None) as batch_op:
        batch_op.create_index(
            "idx_inventory_workspace_created", ["workspace_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_movements_variant_id"), ["variant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_movements_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "order_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("variant_id", sa.String(length=36), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["variant_id"], ["product_variants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_order_items_order_id"), ["order_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_order_items_variant_id"), ["variant_id"], unique=False)

    op.create_table(
        "price_tiers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("variant_id", sa.String(length=36), nullable=False),
        sa.Column("minimum_quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["variant_id"], ["product_variants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("variant_id", "minimum_quantity"),
    )
    with op.batch_alter_table("price_tiers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_price_tiers_variant_id"), ["variant_id"], unique=False)

    op.create_table(
        "product_images",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=True),
        sa.Column("variant_id", sa.String(length=36), nullable=True),
        sa.Column("image_type", sa.String(length=30), nullable=False),
        sa.Column("file_key", sa.String(length=2000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(product_id IS NOT NULL AND variant_id IS NULL) OR (product_id IS NULL AND variant_id IS NOT NULL)",
            name="ck_product_image_single_owner",
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["variant_id"], ["product_variants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("product_images", schema=None) as batch_op:
        batch_op.create_index(
            "idx_product_image_product_type", ["product_id", "image_type"], unique=False
        )
        batch_op.create_index("idx_product_image_variant", ["variant_id"], unique=False)

    op.create_table(
        "quote_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("quote_id", sa.String(length=36), nullable=False),
        sa.Column("variant_id", sa.String(length=36), nullable=False),
        sa.Column("sku_code", sa.String(length=100), nullable=False),
        sa.Column("product_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["quote_id"], ["quotes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["variant_id"], ["product_variants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quote_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_quote_items_quote_id"), ["quote_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_quote_items_variant_id"), ["variant_id"], unique=False)

    op.create_table(
        "quote_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("quote_id", sa.String(length=36), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.Column("subtotal_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("shipping_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("terms", sa.Text(), nullable=False),
        sa.Column("items_snapshot", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["quote_id"], ["quotes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quote_id", "version_number"),
    )
    with op.batch_alter_table("quote_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_quote_versions_quote_id"), ["quote_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("quote_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quote_versions_quote_id"))

    op.drop_table("quote_versions")
    with op.batch_alter_table("quote_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quote_items_variant_id"))
        batch_op.drop_index(batch_op.f("ix_quote_items_quote_id"))

    op.drop_table("quote_items")
    with op.batch_alter_table("product_images", schema=None) as batch_op:
        batch_op.drop_index("idx_product_image_variant")
        batch_op.drop_index("idx_product_image_product_type")

    op.drop_table("product_images")
    with op.batch_alter_table("price_tiers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_price_tiers_variant_id"))

    op.drop_table("price_tiers")
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_items_variant_id"))
        batch_op.drop_index(batch_op.f("ix_order_items_order_id"))

    op.drop_table("order_items")
    with op.batch_alter_table("inventory_movements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_movements_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_movements_variant_id"))
        batch_op.drop_index("idx_inventory_workspace_created")

    op.drop_table("inventory_movements")
    with op.batch_alter_table("shipments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shipments_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_shipments_order_id"))

    op.drop_table("shipments")
    with op.batch_alter_table("quotes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quotes_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_quotes_lead_id"))
        batch_op.drop_index(batch_op.f("ix_quotes_buyer_inquiry_id"))
        batch_op.drop_index("idx_quote_workspace_status")

    op.drop_table("quotes")
    with op.batch_alter_table("product_variants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_variants_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_product_variants_product_id"))

    op.drop_table("product_variants")
    with op.batch_alter_table("agent_approvals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_approvals_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_agent_approvals_status"))
        batch_op.drop_index(batch_op.f("ix_agent_approvals_requested_by"))
        batch_op.drop_index(batch_op.f("ix_agent_approvals_execution_id"))
        batch_op.drop_index("idx_agent_approval_workspace_status")

    op.drop_table("agent_approvals")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_products_workspace_id"))

    op.drop_table("products")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_orders_workspace_id"))

    op.drop_table("orders")
    with op.batch_alter_table("contact_activities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contact_activities_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_contact_activities_lead_id"))
        batch_op.drop_index("idx_activity_workspace_created")

    op.drop_table("contact_activities")
    with op.batch_alter_table("agent_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_messages_conversation_id"))
        batch_op.drop_index("idx_agent_message_conversation_created")

    op.drop_table("agent_messages")
    with op.batch_alter_table("agent_executions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_executions_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_agent_executions_status"))
        batch_op.drop_index(batch_op.f("ix_agent_executions_requested_by"))
        batch_op.drop_index(batch_op.f("ix_agent_executions_conversation_id"))
        batch_op.drop_index("idx_agent_execution_conversation_status")

    op.drop_table("agent_executions")
    with op.batch_alter_table("workspace_prompt_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workspace_prompt_versions_workspace_id"))

    op.drop_table("workspace_prompt_versions")
    with op.batch_alter_table("workspace_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workspace_members_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_workspace_members_user_id"))

    op.drop_table("workspace_members")
    with op.batch_alter_table("workspace_invitations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workspace_invitations_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_workspace_invitations_email"))
        batch_op.drop_index("idx_workspace_invitation_workspace_status")

    op.drop_table("workspace_invitations")
    with op.batch_alter_table("shopify_configs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shopify_configs_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_shopify_configs_is_active"))

    op.drop_table("shopify_configs")
    with op.batch_alter_table("outbox_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outbox_messages_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_outbox_messages_topic"))
        batch_op.drop_index(batch_op.f("ix_outbox_messages_status"))
        batch_op.drop_index("idx_outbox_status_available")

    op.drop_table("outbox_messages")
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_leads_workspace_id"))
        batch_op.drop_index("idx_lead_workspace_stage")

    op.drop_table("leads")
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_idempotency_records_workspace_id"))

    op.drop_table("idempotency_records")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_workspace_id"))

    op.drop_table("categories")
    with op.batch_alter_table("buyer_inquiries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_buyer_inquiries_assigned_workspace_id"))

    op.drop_table("buyer_inquiries")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))
        batch_op.drop_index("idx_audit_workspace_created")

    op.drop_table("audit_logs")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_keys_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_api_keys_user_id"))
        batch_op.drop_index(batch_op.f("ix_api_keys_is_active"))
        batch_op.drop_index("idx_api_key_workspace_active")

    op.drop_table("api_keys")
    with op.batch_alter_table("agent_conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_conversations_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_agent_conversations_user_id"))
        batch_op.drop_index(batch_op.f("ix_agent_conversations_status"))
        batch_op.drop_index("idx_agent_conversation_workspace_user")

    op.drop_table("agent_conversations")
    with op.batch_alter_table("workspaces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workspaces_slug"))

    op.drop_table("workspaces")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_phone"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("supplier_inquiries")
    with op.batch_alter_table("auth_challenges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_challenges_target"))
        batch_op.drop_index(batch_op.f("ix_auth_challenges_channel"))
        batch_op.drop_index("idx_auth_challenge_target_created")
        batch_op.drop_index("idx_auth_challenge_ip_created")

    op.drop_table("auth_challenges")
    # ### end Alembic commands ###
