export type CountryOption = {
  value: string;
  label: string;
  labelEn: string;
};

export const COUNTRY_OPTIONS: readonly CountryOption[] = [
  // --- 亚洲 ---
  { value: "CN", label: "中国", labelEn: "China" },
  { value: "JP", label: "日本", labelEn: "Japan" },
  { value: "KR", label: "韩国", labelEn: "South Korea" },
  { value: "IN", label: "印度", labelEn: "India" },
  { value: "ID", label: "印度尼西亚", labelEn: "Indonesia" },
  { value: "TH", label: "泰国", labelEn: "Thailand" },
  { value: "VN", label: "越南", labelEn: "Vietnam" },
  { value: "MY", label: "马来西亚", labelEn: "Malaysia" },
  { value: "SG", label: "新加坡", labelEn: "Singapore" },
  { value: "PH", label: "菲律宾", labelEn: "Philippines" },
  { value: "PK", label: "巴基斯坦", labelEn: "Pakistan" },
  { value: "BD", label: "孟加拉国", labelEn: "Bangladesh" },
  { value: "MM", label: "缅甸", labelEn: "Myanmar" },
  { value: "KH", label: "柬埔寨", labelEn: "Cambodia" },
  { value: "LA", label: "老挝", labelEn: "Laos" },
  { value: "NP", label: "尼泊尔", labelEn: "Nepal" },
  { value: "LK", label: "斯里兰卡", labelEn: "Sri Lanka" },
  { value: "MN", label: "蒙古", labelEn: "Mongolia" },
  { value: "KP", label: "朝鲜", labelEn: "North Korea" },
  { value: "TW", label: "台湾", labelEn: "Taiwan" },
  { value: "HK", label: "香港", labelEn: "Hong Kong" },
  { value: "MO", label: "澳门", labelEn: "Macau" },

  // --- 中东 ---
  { value: "AE", label: "阿联酋", labelEn: "United Arab Emirates" },
  { value: "SA", label: "沙特阿拉伯", labelEn: "Saudi Arabia" },
  { value: "QA", label: "卡塔尔", labelEn: "Qatar" },
  { value: "KW", label: "科威特", labelEn: "Kuwait" },
  { value: "OM", label: "阿曼", labelEn: "Oman" },
  { value: "BH", label: "巴林", labelEn: "Bahrain" },
  { value: "IL", label: "以色列", labelEn: "Israel" },
  { value: "JO", label: "约旦", labelEn: "Jordan" },
  { value: "LB", label: "黎巴嫩", labelEn: "Lebanon" },
  { value: "IQ", label: "伊拉克", labelEn: "Iraq" },
  { value: "IR", label: "伊朗", labelEn: "Iran" },
  { value: "SY", label: "叙利亚", labelEn: "Syria" },
  { value: "YE", label: "也门", labelEn: "Yemen" },
  { value: "TR", label: "土耳其", labelEn: "Turkey" },

  // --- 欧洲 ---
  { value: "UK", label: "英国", labelEn: "United Kingdom" },
  { value: "FR", label: "法国", labelEn: "France" },
  { value: "DE", label: "德国", labelEn: "Germany" },
  { value: "IT", label: "意大利", labelEn: "Italy" },
  { value: "ES", label: "西班牙", labelEn: "Spain" },
  { value: "NL", label: "荷兰", labelEn: "Netherlands" },
  { value: "BE", label: "比利时", labelEn: "Belgium" },
  { value: "LU", label: "卢森堡", labelEn: "Luxembourg" },
  { value: "CH", label: "瑞士", labelEn: "Switzerland" },
  { value: "AT", label: "奥地利", labelEn: "Austria" },
  { value: "SE", label: "瑞典", labelEn: "Sweden" },
  { value: "NO", label: "挪威", labelEn: "Norway" },
  { value: "DK", label: "丹麦", labelEn: "Denmark" },
  { value: "FI", label: "芬兰", labelEn: "Finland" },
  { value: "IS", label: "冰岛", labelEn: "Iceland" },
  { value: "IE", label: "爱尔兰", labelEn: "Ireland" },
  { value: "PT", label: "葡萄牙", labelEn: "Portugal" },
  { value: "GR", label: "希腊", labelEn: "Greece" },
  { value: "PL", label: "波兰", labelEn: "Poland" },
  { value: "CZ", label: "捷克", labelEn: "Czech Republic" },
  { value: "SK", label: "斯洛伐克", labelEn: "Slovakia" },
  { value: "HU", label: "匈牙利", labelEn: "Hungary" },
  { value: "RO", label: "罗马尼亚", labelEn: "Romania" },
  { value: "BG", label: "保加利亚", labelEn: "Bulgaria" },
  { value: "HR", label: "克罗地亚", labelEn: "Croatia" },
  { value: "SI", label: "斯洛文尼亚", labelEn: "Slovenia" },
  { value: "RS", label: "塞尔维亚", labelEn: "Serbia" },
  { value: "UA", label: "乌克兰", labelEn: "Ukraine" },
  { value: "RU", label: "俄罗斯", labelEn: "Russia" },
  { value: "EE", label: "爱沙尼亚", labelEn: "Estonia" },
  { value: "LV", label: "拉脱维亚", labelEn: "Latvia" },
  { value: "LT", label: "立陶宛", labelEn: "Lithuania" },
  { value: "CY", label: "塞浦路斯", labelEn: "Cyprus" },
  { value: "MT", label: "马耳他", labelEn: "Malta" },

  // --- 北美 ---
  { value: "US", label: "美国", labelEn: "United States" },
  { value: "CA", label: "加拿大", labelEn: "Canada" },
  { value: "MX", label: "墨西哥", labelEn: "Mexico" },
  { value: "PA", label: "巴拿马", labelEn: "Panama" },
  { value: "CR", label: "哥斯达黎加", labelEn: "Costa Rica" },
  { value: "GT", label: "危地马拉", labelEn: "Guatemala" },
  { value: "HN", label: "洪都拉斯", labelEn: "Honduras" },
  { value: "SV", label: "萨尔瓦多", labelEn: "El Salvador" },
  { value: "NI", label: "尼加拉瓜", labelEn: "Nicaragua" },
  { value: "DO", label: "多米尼加", labelEn: "Dominican Republic" },
  { value: "CU", label: "古巴", labelEn: "Cuba" },
  { value: "JM", label: "牙买加", labelEn: "Jamaica" },
  { value: "TT", label: "特立尼达和多巴哥", labelEn: "Trinidad and Tobago" },

  // --- 南美 ---
  { value: "BR", label: "巴西", labelEn: "Brazil" },
  { value: "AR", label: "阿根廷", labelEn: "Argentina" },
  { value: "CL", label: "智利", labelEn: "Chile" },
  { value: "CO", label: "哥伦比亚", labelEn: "Colombia" },
  { value: "PE", label: "秘鲁", labelEn: "Peru" },
  { value: "EC", label: "厄瓜多尔", labelEn: "Ecuador" },
  { value: "VE", label: "委内瑞拉", labelEn: "Venezuela" },
  { value: "UY", label: "乌拉圭", labelEn: "Uruguay" },
  { value: "PY", label: "巴拉圭", labelEn: "Paraguay" },
  { value: "BO", label: "玻利维亚", labelEn: "Bolivia" },

  // --- 大洋洲 ---
  { value: "AU", label: "澳大利亚", labelEn: "Australia" },
  { value: "NZ", label: "新西兰", labelEn: "New Zealand" },
  { value: "FJ", label: "斐济", labelEn: "Fiji" },
  { value: "PG", label: "巴布亚新几内亚", labelEn: "Papua New Guinea" },

  // --- 非洲 ---
  { value: "ZA", label: "南非", labelEn: "South Africa" },
  { value: "NG", label: "尼日利亚", labelEn: "Nigeria" },
  { value: "EG", label: "埃及", labelEn: "Egypt" },
  { value: "KE", label: "肯尼亚", labelEn: "Kenya" },
  { value: "ET", label: "埃塞俄比亚", labelEn: "Ethiopia" },
  { value: "GH", label: "加纳", labelEn: "Ghana" },
  { value: "TZ", label: "坦桑尼亚", labelEn: "Tanzania" },
  { value: "MA", label: "摩洛哥", labelEn: "Morocco" },
  { value: "DZ", label: "阿尔及利亚", labelEn: "Algeria" },
  { value: "TN", label: "突尼斯", labelEn: "Tunisia" },
  { value: "LY", label: "利比亚", labelEn: "Libya" },
  { value: "SD", label: "苏丹", labelEn: "Sudan" },
  { value: "UG", label: "乌干达", labelEn: "Uganda" },
  { value: "RW", label: "卢旺达", labelEn: "Rwanda" },
  { value: "AO", label: "安哥拉", labelEn: "Angola" },
  { value: "CI", label: "科特迪瓦", labelEn: "Côte d'Ivoire" },
  { value: "CM", label: "喀麦隆", labelEn: "Cameroon" },
  { value: "SN", label: "塞内加尔", labelEn: "Senegal" },
  { value: "ZM", label: "赞比亚", labelEn: "Zambia" },
  { value: "ZW", label: "津巴布韦", labelEn: "Zimbabwe" },
  { value: "MU", label: "毛里求斯", labelEn: "Mauritius" },
];
